name: check
on:
  push:
    branches: [main]
  pull_request:

# Set strict permissions at the top level
permissions:
  contents: read

jobs:
  quality-check:
    name: Lint and Security
    runs-on: ubuntu-latest
    steps:
      # Pinning by SHA instead of version tag
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@3041bf56604102f05352ba2bb202f90aef5a3e77 # v5.2.0
        with:
          go-version: '1.21'
          cache: true

      - name: Run quality suite
        # This calls your Makefile: gosec, gitleaks, and tests
        run: make check